[package]
name = "cargo-registry"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.2.2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/crates.io"
description = "Backend of crates.io"
edition = "2021"
default-run = "server"

[workspace]

[profile.release]
opt-level = 2

[lib]
name = "cargo_registry"
doctest = true

[[test]]
name = "all"
path = "src/tests/all.rs"

[dependencies]
anyhow = "=1.0.66"
aws-sigv4 = "=0.51.0"
base64 = "=0.13.1"
cargo-registry-index = { path = "cargo-registry-index" }
cargo-registry-markdown = { path = "cargo-registry-markdown" }
cargo-registry-s3 = { path = "cargo-registry-s3" }
chrono = { version = "=0.4.23", features = ["serde"] }
clap = { version = "=4.0.29", features = ["derive", "unicode", "wrap_help"] }

conduit = "=0.10.0"
conduit-conditional-get = "=0.10.0"
conduit-cookie = "=0.10.0"
conduit-git-http-backend = "=0.10.0"
conduit-hyper = "=0.4.2"
conduit-middleware = "=0.10.0"
conduit-router = "=0.10.0"
conduit-static = "=0.10.1"

cookie = { version = "=0.16.1", features = ["secure"] }
dashmap = { version = "=5.4.0", features = ["raw-api"] }
derive_deref = "=1.1.1"
dialoguer = "=0.10.2"
diesel = { version = "=1.4.8", features = ["postgres", "serde_json", "chrono", "r2d2"] }
diesel_full_text_search = "=1.0.1"
diesel_migrations = { version = "=1.4.0", features = ["postgres"] }
dotenv = "=0.15.0"
flate2 = "=1.0.25"
futures-channel = { version = "=0.3.25", default-features = false }
futures-util = "=0.3.25"
hex = "=0.4.3"
http = "=0.2.8"
hyper = { version = "=0.14.23", features = ["client", "http1"] }
indexmap = { version = "=1.9.2", features = ["serde-1"] }
indicatif = "=0.17.2"
ipnetwork = "=0.20.0"
tikv-jemallocator = { version = "=0.5.0", features = ['unprefixed_malloc_on_supported_platforms', 'profiling'] }
lettre = { version = "=0.10.1", default-features = false, features = ["file-transport", "smtp-transport", "native-tls", "hostname", "builder"] }
minijinja = "=0.26.0"
moka = "=0.9.6"
oauth2 = { version = "=4.3.0", default-features = false, features = ["reqwest"] }
parking_lot = "=0.12.1"
prometheus = { version = "=0.13.3", default-features = false }
rand = "=0.8.5"
reqwest = { version = "=0.11.13", features = ["blocking", "gzip", "json"] }
retry = "=2.0.0"
scheduled-thread-pool = "=0.2.6"
semver = { version = "=1.0.14", features = ["serde"] }
sentry = { version = "=0.29.1", features = ["tracing"] }
sentry-conduit = { version = "=0.29.0", default-features = false }
serde = { version = "=1.0.149", features = ["derive"] }
serde_json = "=1.0.89"
sha2 = "=0.10.6"
spdx = "=0.9.0"
swirl = { git = "https://github.com/sgrif/swirl.git", rev = "e87cf37" }
tar = "=0.4.38"
tempfile = "=3.3.0"
thiserror = "=1.0.37"
tokio = { version = "=1.23.0", features = ["net", "signal", "io-std", "io-util", "rt-multi-thread", "macros"]}
toml = "=0.5.9"
tracing = "=0.1.37"
tracing-subscriber = { version = "=0.3.16", features = ["env-filter"] }
url = "=2.3.1"
sigstore = "0.6.0"

[dev-dependencies]
cargo-registry-index = { path = "cargo-registry-index", features = ["testing"] }
claims = "=0.7.1"
conduit-test = "=0.10.0"
hyper-tls = "=0.5.0"
insta = { version = "=1.22.0", features = ["redactions", "yaml"] }
once_cell = "=1.16.0"
tokio = "=1.23.0"
tower-service = "=0.3.2"

[build-dependencies]
diesel = { version = "=1.4.8", features = ["postgres"] }
diesel_migrations = { version = "=1.4.0", features = ["postgres"] }
dotenv = "=0.15.0"
